### ISSUE TITLE
[Int]::comp_eq is incorrect

### ISSUE THREAD

**Issue by dsprenkels** [denismerigoux/rust-secret-integers#1]
https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=b999231e6eb02b3975fddfd71c5f1d4b

I noticed that `U8::comp_eq` works incorrectly. Without looking into the actual mechanism, I put the code into Godbolt. <https://godbolt.org/z/6ye9CL> suggests that this line

https://github.com/denismerigoux/rust-secret-integers/blob/cd387da02aa03d66dca2c31398eb80799dc5a486/src/lib.rs#L287

should be an XOR operation.

**Comment by denismerigoux** [comment]
Fixed by ecfce67
