### ISSUE TITLE
`[Int]::comp_gte` is incorrect

### ISSUE THREAD

**Issue by 197g** [denismerigoux/rust-secret-integers#3]
https://github.com/denismerigoux/rust-secret-integers/blob/9de08c2172862429c8ab0474c7858fa45fe92d8d/src/lib.rs#L335

That variable naming is inconsistent with the operation. The original implementation also uses proper xor instead of logical or. The operation should probably be explained in a comment as well.

**Comment by denismerigoux** [comment]
Fixed by 8d9d60a
